### Importar librería

In [ ]:
import numpy as np 

In [ ]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
#Validación elemento a elemento
indices_cond = arr > 5 
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
# Seleccion de elementos basados en alguna condición
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
#Usando condiciones más complejas
arr[(arr > 5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[arr > 5] = 99 

In [ ]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)